# Generated by Django 4.0.3 on 2022-03-27 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(default=True, editable=False)),
                ('prefftime1', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 27, 20, 47, 43, 360498))),
                ('prefftime2', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 27, 20, 47, 43, 360515))),
                ('prefftime3', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 27, 20, 47, 43, 360524))),
                ('bit', models.CharField(max_length=10)),
                ('customer', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerData',
        ),
    ]
