# Generated by Django 4.0.3 on 2022-03-27 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_prefftime1_alter_customer_prefftime2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='prefftime1',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 27, 20, 57, 52, 671250)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefftime2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 27, 20, 57, 52, 671267)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefftime3',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 27, 20, 57, 52, 671276)),
        ),
    ]
