# Generated by Django 4.0.3 on 2022-03-29 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_prefftime1_alter_customer_prefftime2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='prefftime1',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 7, 41, 353955), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefftime2',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 7, 41, 353968), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefftime3',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 7, 41, 353977), null=True),
        ),
    ]
