# Generated by Django 4.0.3 on 2022-03-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customer_prefftime1_alter_customer_prefftime2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop_list',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefftime1',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 21, 29, 765333), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefftime2',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 21, 29, 765351), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefftime3',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 21, 29, 765360), null=True),
        ),
    ]
