# Generated by Django 4.0.3 on 2022-03-29 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customer_shop_list_alter_customer_bit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prefftime1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefftime2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefftime3',
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime1_closing',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 31, 33, 445459), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime1_opening',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 31, 33, 445446), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime2_closing',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 31, 33, 445475), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime2_opening',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 31, 33, 445468), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime3_closing',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 31, 33, 445489), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime3_opening',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 17, 31, 33, 445482), null=True),
        ),
    ]
