# Generated by Django 4.0.3 on 2022-03-29 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_customer_prefftime1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prefftime1_closing',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefftime1_opening',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefftime2_closing',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefftime2_opening',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefftime3_closing',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefftime3_opening',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shop_list',
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime1',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 18, 54, 3, 490502), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime2',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 18, 54, 3, 490518), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefftime3',
            field=models.TimeField(default=datetime.datetime(2022, 3, 29, 18, 54, 3, 490532), null=True),
        ),
    ]
