# Generated by Django 4.0.3 on 2022-05-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_customer_prefftime1_alter_customer_prefftime2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alloted_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
