# Generated by Django 4.0.3 on 2022-05-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_customer_alloted_time_customer_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alloted_time',
            field=models.CharField(max_length=10),
        ),
    ]
