# Generated by Django 4.0.3 on 2022-03-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopkeeper',
            old_name='shopkeeper',
            new_name='user',
        ),
    ]
