# Generated by Django 4.0.3 on 2022-03-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_rename_shopkeeper_shopkeeper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='is_customer',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
