# Generated by Django 4.0.3 on 2022-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_alter_shopkeeper_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
    ]
