# Generated by Django 4.0.3 on 2022-03-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_alter_shopkeeper_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='shop_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
