# Generated by Django 4.0.3 on 2022-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0007_auto_20220328_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
